runtime: java11
instance_class: F1

entrypoint: java -jar just-class-backend.jar

automatic_scaling:
  max_instances: 2
  min_instances: 1

inbound_services:
  - warmup

handlers:

env_variables:
  envi: "true"
  GOOGLE_CLOUD_PROJECT: ""
