runtime: java11
instance_class: F1

entrypoint: java -jar just-class-backend.jar

automatic_scaling:
  max_instances: 2
  min_instances: 0

handlers:

env_variables:
  envi: "true"
  GOOGLE_CLOUD_PROJECT: "justclass-da0b0"
  JAVA_TOOL_OPTIONS: "-XX:MaxRAM=256m -XX:ActiveProcessorCount=2 -Xmx32m"
